package tray

import (
	"embed"
	"fmt"
)

// iconFS holds the tinted marks generated by agent/tray/icons/gen.sh from
// icons/warphold.svg: one PNG per tone at panel and HiDPI-panel size.
//
//go:embed icons/*.png
var iconFS embed.FS

// panelIconSize is the size the tray asks for: the 44 px mark, which panels
// scale down cleanly on a 1x display and use as-is on a HiDPI one.
const panelIconSize = 44

// Icon returns the PNG for a tone at 22 or 44 pixels.
func Icon(t Tone, size int) ([]byte, error) {
	b, err := iconFS.ReadFile(fmt.Sprintf("icons/%s-%d.png", t, size))
	if err != nil {
		return nil, fmt.Errorf("no %dpx icon for tone %q: %w", size, t, err)
	}

	return b, nil
}
